gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title

# Setup
title:            DeepNotes
tagline:          'Deep Learning Demystified'
description:      'Deep Learning Demystified'
url:              http://deepnotes.io
baseurl:          /

author:
  name:           'Paras Dahal'
  url:            https://twitter.com/parasdahal
  affiliation:    ''

paginate:         10

# Collections
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/parasdahal/deepnotes
